package cn.guwei.bos.domain.bc;
// Generated 2017-7-18 16:56:03 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.springframework.data.annotation.Transient;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * 分区
 * Subarea generated by hbm2java
 */
@Entity
@Table(name="bc_subarea"
    ,catalog="bos"
)
public class Subarea  implements java.io.Serializable {


     private String id;
     private Decidedzone decidedzone;
     private Region region;
     private String addresskey;
     private String startnum;
     private String endnum;
     private Character single;
     private String position;

    public Subarea() {
    }

    public Subarea(Decidedzone decidedzone, Region region, String addresskey, String startnum, String endnum, Character single, String position) {
       this.decidedzone = decidedzone;
       this.region = region;
       this.addresskey = addresskey;
       this.startnum = startnum;
       this.endnum = endnum;
       this.single = single;
       this.position = position;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")
    @JSONField(name="sid")
    @Column(name="ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
//    @Transient
//    public String getSid(){
//    	return this.id;
//    }
    
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DECIDEDZONE_ID")
//@JSON(serialize=false)
@JSONField(serialize=false)
    public Decidedzone getDecidedzone() {
        return this.decidedzone;
    }
    
    public void setDecidedzone(Decidedzone decidedzone) {
        this.decidedzone = decidedzone;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REGION_ID")
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    
    @Column(name="ADDRESSKEY", length=100)
    public String getAddresskey() {
        return this.addresskey;
    }
    
    public void setAddresskey(String addresskey) {
        this.addresskey = addresskey;
    }
    
    @Column(name="STARTNUM", length=30)
    public String getStartnum() {
        return this.startnum;
    }
    
    public void setStartnum(String startnum) {
        this.startnum = startnum;
    }
    
    @Column(name="ENDNUM", length=30)
    public String getEndnum() {
        return this.endnum;
    }
    
    public void setEndnum(String endnum) {
        this.endnum = endnum;
    }
    
    @Column(name="SINGLE", length=1)
    public Character getSingle() {
        return this.single;
    }
    
    public void setSingle(Character single) {
        this.single = single;
    }
    
    @Column(name="POSITION")
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }




}


